"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\stringPool.asm 
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\table.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\iterativeLoad.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\prepare.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\resolve.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\schedule.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\timer.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\linkedList.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\contextSwitch.asm
"c:\program files\win98ddk\bin\win98\ml.exe" /nologo /c /coff /Sa /Sc /Flout\Release\ /Foout\Release\ out\Release\execute.asm
